Update gradle workflow

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -15,17 +15,20 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v4
     - name: Set up JDK 17
-      uses: actions/setup-java@v2
+      uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: gradle
-    - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
+    - name: Set up Gradle
+      uses: gradle/actions/setup-gradle@v3
+      with:
+        dependency-graph: generate-and-submit
+        artifact-retention-days: 7
     - name: Build with Gradle
-      run: ./gradlew build
+      run: ./gradlew jar
     - name: Push release
       run: |
         cd build/libs || exit 1
@@ -34,7 +37,7 @@ jobs:
         git config --local user.email "41898282+github-actions@users.noreply.github.com"
         git checkout -b release
         git add .
-        git commit -m "Release file"
+        git commit -m "Publish Release for $GITHUB_SHA"
         git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
         git push -f -u origin release
 
@@ -45,24 +48,33 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
         with:
           ref: release
-          path: manhunt
+          path: plugins
       - name: Set up JDK 17
-        uses: actions/setup-java@v2
+        uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
+      - name: Download PaperUpdater
+        uses: robinraju/release-downloader@v1.8
+        with:
+          repository: XZTDean/PaperUpdater
+          latest: true
+          fileName: "PaperUpdater*.jar"
       - name: Download minecraft new build
-        run: wget -q https://papermc.io/api/v2/projects/paper/versions/1.18.1/builds/147/downloads/paper-1.18.1-147.jar -O paper.jar
-      - name: Download needed plugins
-        run: |
-          mkdir plugins && cd plugins
-          wget -q https://dl.isurl.tech/StopServer.jar
-          cp ../manhunt/ManHunt*.jar ./
-          cd ..
+        run: java -jar -Xms1G -Xmx1G PaperUpdater*.jar
+      - name: Download StopServer plugins
+        uses: robinraju/release-downloader@v1.8
+        with:
+          repository: XZTDean/MinecraftStopServer
+          latest: true
+          fileName: "StopServer*.jar"
+          out-file-path: "plugins"
       - name: Agree eula
         run: echo "eula=true" > eula.txt
       - name: Run the game
         run: java -Xms4G -Xmx6G -jar paper.jar --nogui
+      - name: Check error in logs
+        run: if grep "Could not load 'plugins" logs/latest.log || grep "Error occurred while enabling UHC" logs/latest.log; then exit 1; fi
